name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_TOKEN }}
          accountId: 1feef70717b588bffa9cbe216703f20d
          projectName: korea-travel
          directory: .
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
